### PR TITLE
PICARD-1784: fix a typo leading to Coverart error: Host not found

### PR DESCRIPTION
**Pull request by zas**
# Summary

* This is a…
    * [x] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

When downloading PDF cover art images, thumbnail URL is only the first letter of the actual URL.
This leads to various problems.

```
D: 18:12:01,232 coverart.next_in_queue:204: Downloading CaaThumbnailCoverArtImage(url='h', types=['booklet'], support_types=True, support_multi_types=True, is_front=False)
D: 18:12:01,232 webservice.ratecontrol._out_of_backoff:229: ('ia800305.us.archive.org', 80): oobackoff; delay: 1000ms -> 1000ms; slow start; window size 1.000 -> 2.000
D: 18:12:01,233 webservice.ratecontrol.get_delay_to_next_request:113: ('', 80): First request
D: 18:12:01,234 webservice.ratecontrol.increment_requests:138: ('', 80): Incrementing requests to: 1
D: 18:12:01,235 webservice.ratecontrol.decrement_requests:146: ('', 80): Decrementing requests to: 0
E: 18:12:01,236 webservice._handle_reply:396: Network request error for : Host not found (QT code 3, HTTP code 0)
E: 18:12:01,236 album.error_append:278: Coverart error: Host not found
```

* JIRA ticket (_optional_): PICARD-1784

# Solution

It happens only with releases having PDF cover art images from CAA, and when those images are actually downloaded by Picard (depending on selected options), but it was there since years

This issue was introduced in 30635246f6e13d6b46b61dd38c4aaa82ad4c9c88

That's a typo: `url[0]` -> `urls[0]` (hence the 'h')

# Action

### CODE REVIEW

**Comment by zas** [comment]
> But could you actually reproduce the crash also reported in this issue? I can't here.

Yes, I could, and with this fix, it doesn't happen.

```
Traceback (most recent call last):
  File "./picard/ui/coverartbox.py", line 342, in show_cover_art_info
    self.parent.view_info(default_tab=1)
  File "./picard/ui/mainwindow.py", line 1042, in view_info
    dialog = AlbumInfoDialog(album, self)
  File "./picard/ui/infodialog.py", line 305, in __init__
    super().__init__(album, parent)
  File "./picard/ui/infodialog.py", line 153, in __init__
    self._display_tabs()
  File "./picard/ui/infodialog.py", line 158, in _display_tabs
    self._display_artwork_tab()
  File "./picard/ui/infodialog.py", line 237, in _display_artwork_tab
    self._display_artwork(self.images, self.artwork_table._new_cover_col)
  File "./picard/ui/infodialog.py", line 181, in _display_artwork
    data = image.thumbnail.data
  File "./picard/coverart/image.py", line 357, in data
    return self.datahash.data
AttributeError: 'NoneType' object has no attribute 'data'
Abandon (core dumped)
```

Not sure if we should do more than this fix, as it is a direct consequence of this typo. But perhaps there are other cases leading to this crash.
We need tests for this code, I'll try to add some, plus some cleanup, in another PR.
