### PR TITLE
PICARD-2910: Fix AttributeError: 'ScriptEditorDialog' object has no attribute 'uns…

### PR DESCRIPTION
**Pull request by zas**
…aved_changes_confirmation'

Traceback (most recent call last):
  File "/home/zas/src/picard/./picard/ui/mainwindow/__init__.py", line 300, in closeEvent
    if not self.script_editor_dialog.unsaved_changes_confirmation():
AttributeError: 'ScriptEditorDialog' object has no attribute 'unsaved_changes_confirmation'. Did you mean: 'unsaved_changes_in_profile_confirmation'?

This issue was introduced in e253ef4956fc6150be278613a515bce4619b6290

# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): [PICARD-2910](https://tickets.metabrainz.org/browse/PICARD-2910)

# Solution

# Action

Additional actions required:
* [ ] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

### CODE REVIEW

**Review by phw — APPROVED** [review]

**Review by phw — APPROVED** [review]
I guess this is a candidate to backport for a 2.x release then.

**Comment by phw** [comment]
https://github.com/metabrainz/picard/commit/c7744656053ba67c99c8e3fa2493aa5eff9b1c4b
